/*
Package exec GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package exec

func (v *Command) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Args":
			return []string{}, true
		case "WorkDir":
			return []string{}, true
		case "Flags":
			return []string{}, true
		case "Env":
			return []string{}, true
		case "UID":
			return []string{}, true
		case "GID":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (*Env) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (*Flags) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
