/*
Package pgctl GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package pgctl

func (v *Controller) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.Conf, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v *Daemon) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Off":
			return []string{
				"WithoutPg serve without postgres",
			}, true
		case "ExitOnError":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *ErrPostgresNotReady) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Reason":
			return []string{}, true
		}

		return nil, false
	}
	return []string{}, true
}

func (v *Event) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Type":
			return []string{}, true
		case "Data":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (*EventType) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (v *Postgres) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.Conf, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
