/*
Package postgresoperatorclient GENERATED BY gengo:client
DON'T EDIT THIS FILE
*/
package postgresoperatorclient

import (
	archivev1 "github.com/innoai-tech/postgres-operator/pkg/apis/archive/v1"
	courier "github.com/octohelm/courier/pkg/courier"
	courierhttp "github.com/octohelm/courier/pkg/courierhttp"
	metav1 "github.com/octohelm/objectkind/pkg/apis/meta/v1"
	sqltypetime "github.com/octohelm/storage/pkg/sqltype/time"
)

type Readiness struct {
	courierhttp.MethodGet `path:"/api/postgres-operator/v1/status/readiness"`

	ReadinessParameters
}

type ReadinessParameters struct{}

func (Readiness) ResponseData() *ReadinessResponse {
	return new(ReadinessResponse)
}

type Liveness struct {
	courierhttp.MethodGet `path:"/api/postgres-operator/v1/status/liveness"`

	LivenessParameters
}

type LivenessParameters struct{}

func (Liveness) ResponseData() *LivenessResponse {
	return new(LivenessResponse)
}

type CurrentRestoreRequest struct {
	courierhttp.MethodGet `path:"/api/postgres-operator/v1/archive/request-restore"`

	CurrentRestoreRequestParameters
}

type CurrentRestoreRequestParameters struct{}

func (CurrentRestoreRequest) ResponseData() *CurrentRestoreRequestResponse {
	return new(CurrentRestoreRequestResponse)
}

type CancelRestoreRequest struct {
	courierhttp.MethodDelete `path:"/api/postgres-operator/v1/archive/request-restore"`

	CancelRestoreRequestParameters
}

type CancelRestoreRequestParameters struct{}

func (CancelRestoreRequest) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

type DeleteArchive struct {
	courierhttp.MethodDelete `path:"/api/postgres-operator/v1/archive/archives/{archiveCode}"`

	DeleteArchiveParameters
}

type DeleteArchiveParameters struct {
	ArchiveCode ArchiveV1ArchiveCode `name:"archiveCode" in:"path"`
}

func (DeleteArchive) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

type ListArchive struct {
	courierhttp.MethodGet `path:"/api/postgres-operator/v1/archive/archives"`

	ListArchiveParameters
}

type ListArchiveParameters struct{}

func (ListArchive) ResponseData() *ListArchiveResponse {
	return new(ListArchiveResponse)
}

type CreateArchive struct {
	courierhttp.MethodPost `path:"/api/postgres-operator/v1/archive/archives"`

	CreateArchiveParameters
}

type CreateArchiveParameters struct{}

func (CreateArchive) ResponseData() *CreateArchiveResponse {
	return new(CreateArchiveResponse)
}

type RequestRestoreArchive struct {
	courierhttp.MethodPut `path:"/api/postgres-operator/v1/archive/archives/{archiveCode}/restore-request"`

	RequestRestoreArchiveParameters
}

type RequestRestoreArchiveParameters struct {
	ArchiveCode ArchiveV1ArchiveCode `name:"archiveCode" in:"path"`
}

func (RequestRestoreArchive) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

type Restart struct {
	courierhttp.MethodPost `path:"/api/postgres-operator/v1/service/restart"`

	RestartParameters
}

type RestartParameters struct{}

func (Restart) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

type (
	ArchiveV1Archive              = archivev1.Archive
	ArchiveV1ArchiveAsList        = metav1.List[archivev1.Archive]
	ArchiveV1ArchiveCode          = archivev1.ArchiveCode
	ArchiveV1File                 = archivev1.File
	CreateArchiveResponse         = archivev1.Archive
	CurrentRestoreRequestResponse = archivev1.Archive
	ListArchiveResponse           = metav1.List[archivev1.Archive]
	LivenessResponse              = map[string]any
)

type ReadinessResponse = map[string]any

type SqltypeTimeTimestamp = sqltypetime.Timestamp
