/*
Package v1 GENERATED BY gengo:enum
DON'T EDIT THIS FILE
*/
package v1

import (
	errors "errors"
	fmt "fmt"
)

var InvalidCurrency = errors.New("invalid Currency")

func (Currency) EnumValues() []any {
	return []any{
		CurrencyCNY,
	}
}

func ParseCurrencyLabelString(label string) (Currency, error) {
	switch label {
	case "人民币":
		return CurrencyCNY, nil

	default:
		return "", InvalidCurrency
	}
}

func (v Currency) Label() string {
	switch v {
	case CurrencyCNY:
		return "人民币"

	default:
		return fmt.Sprint(v)
	}
}
