/*
Package archive GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package archive

func (v *CancelRestoreRequest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{}, true
}

func (v *CreateArchive) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{
		"ImportArchive",
	}, true
}

func (v *CurrentRestoreRequest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{}, true
}

func (v *DeleteArchive) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ArchiveCode":
			return []string{}, true
		}

		return nil, false
	}
	return []string{}, true
}

func (v *ExportArchiveAsTar) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ArchiveCode":
			return []string{}, true
		}

		return nil, false
	}
	return []string{}, true
}

func (v *ImportArchiveFromTar) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ArchiveCode":
			return []string{}, true
		case "Body":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *ListArchive) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{}, true
}

func (v *RequestRestoreArchive) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ArchiveCode":
			return []string{}, true
		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
