/*
Package archive GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package archive

import (
	context "context"
	fmt "fmt"

	pgctl "github.com/innoai-tech/postgres-operator/pkg/pgctl"
)

func (v *CancelRestoreRequest) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}

func (v *CreateArchive) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}

func (v *CurrentRestoreRequest) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}

func (v *DeleteArchive) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}

func (v *ExportArchiveAsTar) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}

func (v *ImportArchiveFromTar) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}

func (v *ListArchive) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}

func (v *RequestRestoreArchive) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}
