/*
Package operator GENERATED BY gengo:operator
DON'T EDIT THIS FILE
*/
package operator

import (
	courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(courier.NewRouter(&BaseURL{}))
}

func (BaseURL) ResponseContent() any {
	return new(map[string]string)
}

func (BaseURL) ResponseData() *map[string]string {
	return new(map[string]string)
}

func init() {
	R.Register(courier.NewRouter(&ValidAccount{}))
}

func (ValidAccount) ResponseContent() any {
	return nil
}

func (ValidAccount) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}
