/*
Package main GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package main

func (v *Server) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "WebUI":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.Server, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v *SingleNode) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "KeySet":
			return []string{}, true
		case "Sign":
			return []string{}, true
		case "Enc":
			return []string{}, true
		case "AuthService":
			return []string{}, true
		case "MetricExporter":
			return []string{}, true
		case "Daemon":
			return []string{}, true
		case "AutoArchiver":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(&v.Otel, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Controller, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Server, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"serve single-node",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
