/*
Package main GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package main

import (
	context "context"
)

func (v *Server) Init(ctx context.Context) error {
	if err := v.beforeInit(ctx); err != nil {
		return err
	}
	if err := v.Server.Init(ctx); err != nil {
		return err
	}

	return nil
}
