/*
Package db GENERATED BY gengo:operator
DON'T EDIT THIS FILE
*/
package db

import (
	courier "github.com/octohelm/courier/pkg/courier"
	metav1 "github.com/octohelm/objectkind/pkg/apis/meta/v1"

	databasev1 "github.com/innoai-tech/postgres-operator/pkg/apis/database/v1"
)

func init() {
	R.Register(courier.NewRouter(&ListDatabase{}))
}

func (ListDatabase) ResponseContent() any {
	return new(metav1.List[databasev1.Database])
}

func (ListDatabase) ResponseData() *metav1.List[databasev1.Database] {
	return new(metav1.List[databasev1.Database])
}

func init() {
	R.Register(courier.NewRouter(&ListTableOfDatabase{}))
}

func (ListTableOfDatabase) ResponseContent() any {
	return new(metav1.List[databasev1.Table])
}

func (ListTableOfDatabase) ResponseData() *metav1.List[databasev1.Table] {
	return new(metav1.List[databasev1.Table])
}

func init() {
	R.Register(courier.NewRouter(&QueryDatabase{}))
}

func (QueryDatabase) ResponseContent() any {
	return new(databasev1.Result)
}

func (QueryDatabase) ResponseData() *databasev1.Result {
	return new(databasev1.Result)
}
