/*
Package v1 GENERATED BY gengo:objectkind
DON'T EDIT THIS FILE
*/
package v1

func (Column) GetKind() string {
	return "Column"
}

func (Column) GetPluralizedKind() string {
	return "Columns"
}

func (Column) GetAPIVersion() string {
	return SchemeGroupVersion.String()
}

func (Constraint) GetKind() string {
	return "Constraint"
}

func (Constraint) GetPluralizedKind() string {
	return "Constraints"
}

func (Constraint) GetAPIVersion() string {
	return SchemeGroupVersion.String()
}

func (Database) GetKind() string {
	return "Database"
}

func (Database) GetPluralizedKind() string {
	return "Databases"
}

func (Database) GetAPIVersion() string {
	return SchemeGroupVersion.String()
}

func (Result) GetKind() string {
	return "Result"
}

func (Result) GetPluralizedKind() string {
	return "Results"
}

func (Result) GetAPIVersion() string {
	return SchemeGroupVersion.String()
}

func (Table) GetKind() string {
	return "Table"
}

func (Table) GetPluralizedKind() string {
	return "Tables"
}

func (Table) GetAPIVersion() string {
	return SchemeGroupVersion.String()
}
