/*
Package service GENERATED BY gengo:operator
DON'T EDIT THIS FILE
*/
package service

import (
	courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(courier.NewRouter(&Restart{}))
}

func (Restart) ResponseContent() any {
	return nil
}

func (Restart) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}
