/*
Package service GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package service

import (
	context "context"
	fmt "fmt"

	pgctl "github.com/innoai-tech/postgres-operator/pkg/pgctl"
)

func (v *Restart) Init(ctx context.Context) error {
	if value, ok := pgctl.ControllerFromContext(ctx); ok {
		v.c = value
	} else {
		return fmt.Errorf("missing provider %T.c", v)
	}

	return nil
}
