/*
Package v1 GENERATED BY gengo:objectkind
DON'T EDIT THIS FILE
*/
package v1

func (Archive) GetKind() string {
	return "Archive"
}

func (Archive) GetPluralizedKind() string {
	return "Arc"
}

func (Archive) GetAPIVersion() string {
	return SchemeGroupVersion.String()
}
